Repository pepoeverton/web-release-test, pull requests merged in 2021-12, with the labels that each got.

#19 refactor: refactor app text
  src/App.vue
Labels: fix, feature, test

#20 feat: add new text message
  src/App.vue
Labels: fix, feature, test

#21 fix: fix pre-release flag if this flag was marked when creating the release
  .github/workflows/create-changelog.yml
Labels: fix

#22 Develop to main
  .github/workflows/create-changelog.yml
Labels: Deploy

#23 feat: add new button text
  src/App.vue
Labels: feature

#24 Develop to main
  src/App.vue
Labels: Deploy

#25 Corrigindo um problema no uso do actions/checkout@v2
  .github/workflows/bump-version.yml
Labels: fix

#26 Adicionando a Feature chablau
  src/App.vue
Labels: feature

#27 Develop to main
  .github/workflows/bump-version.yml
  src/App.vue
Labels: Deploy

#29 Corrigindo a margin top da página
  src/App.vue
Labels: fix

#28 Corrigindo a cor dos textos
  src/App.vue
Labels: fix

#30 Develop to main
  src/App.vue
Labels: Deploy
